package com.minogatv.box.core.model

import com.minogatv.box.core.model.enums.ProfileType

/**
 * Domain model for a user profile.
 *
 * Each profile is independent: it has its own favourites list, watch history,
 * playlist visibility, and parental-control PIN.
 *
 * @param id        Unique profile ID (auto-generated by Room)
 * @param name      Display name ("Main", "Kids", "Sports", or custom)
 * @param type      One of the preset [ProfileType] values
 * @param pinHash   BCrypt hash of the 4-digit parental-control PIN, or null if not set
 * @param avatarUri Optional URI pointing to a locally stored avatar image
 * @param createdAt Creation timestamp (epoch ms)
 * @param isActive  Whether this profile is currently selected
 */
data class UserProfile(
    val id: Long = 0,
    val name: String,
    val type: ProfileType = ProfileType.MAIN,
    val pinHash: String? = null,
    val avatarUri: String? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val isActive: Boolean = false,
)
